'''
Схемы данных (удобная аннотация и создание) + автовалидация +
+ крутые фишки по типу конвертации в json - pydentic
'''
from typing import Optional

from pydantic import BaseModel


class Table(BaseModel):
    """
    add supporting for accessing pydentic classes` poles via attribute
    (by default - only via dict notation)
    """
    class Config:
        from_attributes: True

class Developer(Table):
    id: Optional[int] = None # must be autogenerated in models
    keyword: str
    jurisdiction: str
    main_company: str

class User(Table):
    id: Optional[str] = None

# ==== schemas for Redo:

class DeveloperRedo(Table):
    ''' all poles here are optional to change '''
    keyword: Optional[str] = None
    jurisdiction: Optional[str] = None
